spring.application.name=leaveapp
spring.datasource.url=jdbc:mysql://localhost:3306/leave_management
spring.datasource.username=root
spring.datasource.password=pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show=true
spring.jpa.properties.hiberate.formate_sql=true
